import { createClient } from '@/lib/supabase/server';
import { getWorkflow } from '@/lib/db/workflows';
import { runWorkflow } from '@/lib/workflow/engine';
import { MORNING_BRIEFING_STEPS } from '@/lib/workflow/steps';
import type { WorkflowStep } from '@/lib/workflow/steps';
import { createBriefing } from '@/lib/db/briefings';
import type { BriefingSection } from '@/lib/types';

export const maxDuration = 300;

const BRIEFING_WORKFLOW_NAMES = [
  'Morning Intelligence Briefing',
  'Morning Briefing',
  'Daily Briefing',
  'Intelligence Briefing',
];

function isBriefingWorkflow(name: string): boolean {
  return BRIEFING_WORKFLOW_NAMES.some(n =>
    name.toLowerCase().includes(n.toLowerCase().split(' ')[0]) &&
    name.toLowerCase().includes('brief')
  ) || name.toLowerCase().includes('morning');
}

function buildBriefingSections(outputs: Record<string, string>): BriefingSection[] {
  const sections: BriefingSection[] = [];

  if (outputs.research_output) {
    sections.push({
      id: crypto.randomUUID(),
      title: 'Competitive Intelligence',
      type: 'recommendations',
      summary: 'Morning competitive scan and market analysis',
      items: [{ id: crypto.randomUUID(), content: outputs.research_output, priority: 'high' }],
    });
  }
  if (outputs.marketing_output) {
    sections.push({
      id: crypto.randomUUID(),
      title: 'Content & Growth Strategy',
      type: 'opportunities',
      summary: 'Marketing recommendations based on intelligence',
      items: [{ id: crypto.randomUUID(), content: outputs.marketing_output, priority: 'medium' }],
    });
  }
  if (outputs.ceo_summary) {
    sections.push({
      id: crypto.randomUUID(),
      title: 'Executive Priorities',
      type: 'priorities',
      summary: 'Strategic synthesis and action directives',
      items: [{ id: crypto.randomUUID(), content: outputs.ceo_summary, priority: 'critical' }],
    });
  }

  return sections;
}

export async function POST(request: Request, { params }: { params: { id: string } }) {
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) return new Response('Unauthorized', { status: 401 });

  if (!process.env.ANTHROPIC_API_KEY) {
    const enc = new TextEncoder();
    return new Response(
      enc.encode(`data: ${JSON.stringify({ type: 'error', message: 'ANTHROPIC_API_KEY is not configured.' })}\n\n`),
      { headers: { 'Content-Type': 'text/event-stream', 'Cache-Control': 'no-cache' } }
    );
  }

  const workflow = await getWorkflow(supabase, params.id, user.id);
  if (!workflow) return new Response('Not found', { status: 404 });

  const dbSteps = (workflow as unknown as { steps?: WorkflowStep[] }).steps ?? [];
  const steps: WorkflowStep[] = dbSteps.length > 0
    ? dbSteps
    : isBriefingWorkflow(workflow.name)
      ? MORNING_BRIEFING_STEPS
      : [];

  if (steps.length === 0) {
    const enc = new TextEncoder();
    return new Response(
      enc.encode(`data: ${JSON.stringify({ type: 'error', message: 'This workflow has no steps configured.' })}\n\n`),
      { headers: { 'Content-Type': 'text/event-stream', 'Cache-Control': 'no-cache' } }
    );
  }

  const agentNames = steps.map(s => `${s.agentRole.charAt(0).toUpperCase() + s.agentRole.slice(1)} Agent`);
  const enc = new TextEncoder();
  const emit = (data: object) => enc.encode(`data: ${JSON.stringify(data)}\n\n`);

  const body = new ReadableStream({
    async start(controller) {
      const outputs: Record<string, string> = {};
      let executionId = '';

      try {
        for await (const event of runWorkflow({
          supabase,
          userId: user.id,
          workflowId: params.id,
          workflowName: workflow.name,
          steps,
          agentNames,
        })) {
          controller.enqueue(emit(event));

          if (event.type === 'token' && event.text) {
            const key = steps[event.stepIndex ?? 0]?.outputKey;
            if (key) outputs[key] = (outputs[key] ?? '') + event.text;
          }
          if (event.type === 'workflow_complete') {
            executionId = event.executionId ?? '';
          }
        }

        if (isBriefingWorkflow(workflow.name) && Object.keys(outputs).length > 0) {
          const sections = buildBriefingSections(outputs);
          const briefingData = await createBriefing(supabase, user.id, {
            date: new Date().toISOString().split('T')[0],
            classification: 'CONFIDENTIAL — OPERATOR LEVEL',
            executive_summary: outputs.ceo_summary
              ? outputs.ceo_summary.slice(0, 400) + (outputs.ceo_summary.length > 400 ? '…' : '')
              : 'Generated by autonomous workflow engine.',
            system_score: 91,
            generated_by: 'NYX Autonomous Workflow Engine',
            generated_at: new Date().toISOString(),
            sections,
          });
          controller.enqueue(emit({ type: 'briefing_created', briefingId: briefingData.id }));
        }
      } catch (e: unknown) {
        controller.enqueue(emit({ type: 'error', message: (e as Error).message }));
      } finally {
        controller.close();
      }
    },
  });

  return new Response(body, {
    headers: {
      'Content-Type': 'text/event-stream',
      'Cache-Control': 'no-cache',
      'X-Accel-Buffering': 'no',
    },
  });
}
