import type { Workflow, Agent, Task, Execution, Briefing } from './types';

// ── WORKFLOWS ────────────────────────────────────────────────────────────────

export const workflows: Workflow[] = [
  {
    id: 'wf-001',
    name: 'Competitor Intelligence',
    description: 'Scrapes competitor websites, product pages, pricing, and news. Compiles into structured intelligence report.',
    trigger: 'scheduled',
    schedule: 'Daily 06:00 UTC',
    status: 'active',
    lastRun: '2026-06-08T06:00:00Z',
    nextRun: '2026-06-09T06:00:00Z',
    agentIds: ['agent-research', 'agent-ceo'],
    runCount: 142,
    successRate: 97.2,
    avgDuration: 284,
    createdAt: '2025-11-14T00:00:00Z',
    tags: ['research', 'competitive', 'automated'],
  },
  {
    id: 'wf-002',
    name: 'Weekly Executive Briefing',
    description: 'Aggregates performance data, key developments, and strategic signals into a classified executive briefing.',
    trigger: 'scheduled',
    schedule: 'Monday 05:00 UTC',
    status: 'active',
    lastRun: '2026-06-02T05:00:00Z',
    nextRun: '2026-06-09T05:00:00Z',
    agentIds: ['agent-ceo', 'agent-research', 'agent-finance'],
    runCount: 28,
    successRate: 100,
    avgDuration: 412,
    createdAt: '2025-12-01T00:00:00Z',
    tags: ['briefing', 'strategy', 'weekly'],
  },
  {
    id: 'wf-003',
    name: 'Lead Qualification Engine',
    description: 'Evaluates inbound leads against ICP. Scores, enriches, and routes to appropriate sales sequence.',
    trigger: 'webhook',
    schedule: null,
    status: 'running',
    lastRun: '2026-06-08T11:22:00Z',
    nextRun: null,
    agentIds: ['agent-sales', 'agent-research'],
    runCount: 891,
    successRate: 94.1,
    avgDuration: 48,
    createdAt: '2025-10-30T00:00:00Z',
    tags: ['sales', 'leads', 'realtime'],
  },
  {
    id: 'wf-004',
    name: 'Startup Validation Framework',
    description: 'Validates new startup ideas against market size, competition, timing, and founder-market fit signals.',
    trigger: 'manual',
    schedule: null,
    status: 'active',
    lastRun: '2026-06-07T14:30:00Z',
    nextRun: null,
    agentIds: ['agent-research', 'agent-ceo'],
    runCount: 17,
    successRate: 100,
    avgDuration: 720,
    createdAt: '2026-01-08T00:00:00Z',
    tags: ['research', 'strategy', 'manual'],
  },
  {
    id: 'wf-005',
    name: 'Content Operations',
    description: 'Generates SEO content, LinkedIn posts, and newsletter sections from research briefs and trend signals.',
    trigger: 'scheduled',
    schedule: 'Wed & Fri 08:00 UTC',
    status: 'active',
    lastRun: '2026-06-07T08:00:00Z',
    nextRun: '2026-06-10T08:00:00Z',
    agentIds: ['agent-marketing'],
    runCount: 64,
    successRate: 96.9,
    avgDuration: 195,
    createdAt: '2025-12-18T00:00:00Z',
    tags: ['marketing', 'content', 'seo'],
  },
  {
    id: 'wf-006',
    name: 'Financial Signal Monitor',
    description: 'Monitors macro signals, portfolio news, FX rates, and key financial indicators. Alerts on threshold breaches.',
    trigger: 'scheduled',
    schedule: 'Hourly',
    status: 'active',
    lastRun: '2026-06-08T11:00:00Z',
    nextRun: '2026-06-08T12:00:00Z',
    agentIds: ['agent-finance'],
    runCount: 2184,
    successRate: 99.8,
    avgDuration: 22,
    createdAt: '2025-09-20T00:00:00Z',
    tags: ['finance', 'monitoring', 'alerts'],
  },
  {
    id: 'wf-007',
    name: 'Meeting Intelligence',
    description: 'Processes meeting transcripts, extracts action items, assigns tasks, and updates project records automatically.',
    trigger: 'webhook',
    schedule: null,
    status: 'paused',
    lastRun: '2026-06-05T16:44:00Z',
    nextRun: null,
    agentIds: ['agent-ceo', 'agent-developer'],
    runCount: 203,
    successRate: 98.5,
    avgDuration: 67,
    createdAt: '2026-01-22T00:00:00Z',
    tags: ['productivity', 'meetings', 'automation'],
  },
  {
    id: 'wf-008',
    name: 'Developer Ops Audit',
    description: 'Reviews codebase health, dependency vulnerabilities, test coverage gaps, and deployment pipeline status.',
    trigger: 'scheduled',
    schedule: 'Daily 02:00 UTC',
    status: 'error',
    lastRun: '2026-06-08T02:00:00Z',
    nextRun: '2026-06-09T02:00:00Z',
    agentIds: ['agent-developer'],
    runCount: 89,
    successRate: 88.8,
    avgDuration: 340,
    createdAt: '2026-02-10T00:00:00Z',
    tags: ['engineering', 'devops', 'audit'],
  },
];

// ── AGENTS ───────────────────────────────────────────────────────────────────

export const agents: Agent[] = [
  {
    id: 'agent-ceo',
    name: 'Strategic Command',
    role: 'ceo',
    purpose: 'Synthesizes intelligence from all agents into strategic decisions. Owns the executive briefing, sets priorities, and approves high-stakes actions.',
    status: 'active',
    currentTask: 'Synthesizing Q2 competitive landscape into board memo',
    model: 'claude-opus-4-8',
    capabilities: ['Strategic synthesis', 'Decision framing', 'Executive communication', 'Priority sequencing', 'Risk assessment'],
    lastActive: '2026-06-08T11:18:00Z',
    metrics: {
      tasksCompleted: 1847,
      successRate: 99.1,
      avgResponseTime: 4.2,
      tokensUsed: 8420000,
      uptime: 99.7,
    },
    recentActivity: [
      { id: 'a1', timestamp: '2026-06-08T11:18:00Z', action: 'Generated board memo draft', result: 'Sent to review queue', status: 'success' },
      { id: 'a2', timestamp: '2026-06-08T09:02:00Z', action: 'Reviewed competitor intelligence report', result: 'Flagged 3 critical signals', status: 'success' },
      { id: 'a3', timestamp: '2026-06-08T06:01:00Z', action: 'Produced executive briefing', result: 'Briefing published to /briefings', status: 'success' },
      { id: 'a4', timestamp: '2026-06-07T14:30:00Z', action: 'Ran startup validation on "NexusAI"', result: 'Scored 74/100 — recommend monitor', status: 'info' },
    ],
  },
  {
    id: 'agent-research',
    name: 'Intelligence Analyst',
    role: 'research',
    purpose: 'Deep research on markets, competitors, technologies, and signals. Produces structured intelligence reports with source citations.',
    status: 'busy',
    currentTask: 'Mapping Series B funding landscape in enterprise AI (Q2 2026)',
    model: 'claude-sonnet-4-6',
    capabilities: ['Web research', 'Data synthesis', 'Trend identification', 'Source verification', 'Competitive mapping'],
    lastActive: '2026-06-08T11:23:00Z',
    metrics: {
      tasksCompleted: 4218,
      successRate: 97.4,
      avgResponseTime: 12.8,
      tokensUsed: 22100000,
      uptime: 98.9,
    },
    recentActivity: [
      { id: 'a5', timestamp: '2026-06-08T11:23:00Z', action: 'Researching Q2 AI funding landscape', result: 'In progress — 67% complete', status: 'info' },
      { id: 'a6', timestamp: '2026-06-08T10:44:00Z', action: 'Competitor report: Anthropic pricing changes', result: '12-page analysis delivered', status: 'success' },
      { id: 'a7', timestamp: '2026-06-08T07:22:00Z', action: 'Scraped 14 competitor sites', result: '842 signals extracted', status: 'success' },
      { id: 'a8', timestamp: '2026-06-07T19:05:00Z', action: 'Market sizing: autonomous agents sector', result: 'TAM estimated at $82B by 2028', status: 'success' },
    ],
  },
  {
    id: 'agent-marketing',
    name: 'Growth Engine',
    role: 'marketing',
    purpose: 'Operates the full content and growth stack. Writes, schedules, and optimizes content across channels. Monitors brand signals.',
    status: 'active',
    currentTask: 'Drafting LinkedIn article: "Why autonomous AI changes the operator, not just the operation"',
    model: 'claude-sonnet-4-6',
    capabilities: ['Content creation', 'SEO optimization', 'Campaign planning', 'Brand monitoring', 'Performance analysis'],
    lastActive: '2026-06-08T11:10:00Z',
    metrics: {
      tasksCompleted: 2103,
      successRate: 96.8,
      avgResponseTime: 7.1,
      tokensUsed: 11800000,
      uptime: 97.4,
    },
    recentActivity: [
      { id: 'a9', timestamp: '2026-06-08T11:10:00Z', action: 'Writing LinkedIn article', result: 'Draft 1 complete — in review', status: 'info' },
      { id: 'a10', timestamp: '2026-06-07T08:02:00Z', action: 'Published 3 SEO articles', result: '4,200 impressions projected', status: 'success' },
      { id: 'a11', timestamp: '2026-06-06T14:30:00Z', action: 'Analyzed newsletter open rates', result: 'Recommended subject line A/B test', status: 'success' },
      { id: 'a12', timestamp: '2026-06-05T09:00:00Z', action: 'Brand mention sweep', result: '14 mentions tracked, 2 flagged', status: 'success' },
    ],
  },
  {
    id: 'agent-sales',
    name: 'Revenue Intelligence',
    role: 'sales',
    purpose: 'Manages the revenue pipeline. Qualifies leads, researches prospects, drafts outreach, and monitors deal signals.',
    status: 'busy',
    currentTask: 'Processing 8 inbound leads from waitlist (scoring against ICP)',
    model: 'claude-sonnet-4-6',
    capabilities: ['Lead qualification', 'Prospect research', 'Outreach drafting', 'Pipeline analysis', 'Deal intelligence'],
    lastActive: '2026-06-08T11:22:00Z',
    metrics: {
      tasksCompleted: 3841,
      successRate: 94.2,
      avgResponseTime: 5.8,
      tokensUsed: 16400000,
      uptime: 99.1,
    },
    recentActivity: [
      { id: 'a13', timestamp: '2026-06-08T11:22:00Z', action: 'Qualifying 8 waitlist leads', result: 'In progress — 3/8 scored', status: 'info' },
      { id: 'a14', timestamp: '2026-06-08T10:15:00Z', action: 'Researched Founder: Alex Chen / Meridian Capital', result: 'High ICP match — routed to Operator tier', status: 'success' },
      { id: 'a15', timestamp: '2026-06-08T08:44:00Z', action: 'Drafted outreach for 5 prospects', result: 'Sent for human approval', status: 'success' },
      { id: 'a16', timestamp: '2026-06-07T16:30:00Z', action: 'Pipeline health analysis', result: '$280K ARR in active stages', status: 'success' },
    ],
  },
  {
    id: 'agent-finance',
    name: 'Financial Operator',
    role: 'finance',
    purpose: 'Monitors financial signals, tracks KPIs, models scenarios, and surfaces anomalies in real time.',
    status: 'active',
    currentTask: null,
    model: 'claude-haiku-4-5-20251001',
    capabilities: ['Financial modeling', 'KPI monitoring', 'Anomaly detection', 'Scenario analysis', 'Cash flow tracking'],
    lastActive: '2026-06-08T11:00:00Z',
    metrics: {
      tasksCompleted: 12440,
      successRate: 99.8,
      avgResponseTime: 1.4,
      tokensUsed: 4200000,
      uptime: 99.97,
    },
    recentActivity: [
      { id: 'a17', timestamp: '2026-06-08T11:00:00Z', action: 'Hourly financial signal scan', result: 'No anomalies detected', status: 'success' },
      { id: 'a18', timestamp: '2026-06-08T10:00:00Z', action: 'MRR reconciliation', result: '$142,400 confirmed — on track', status: 'success' },
      { id: 'a19', timestamp: '2026-06-08T07:00:00Z', action: 'FX rate monitor alert', result: 'EUR/USD breach flagged (+0.8% deviation)', status: 'warn' },
      { id: 'a20', timestamp: '2026-06-07T18:00:00Z', action: 'Burn rate analysis', result: '14.2 months runway at current pace', status: 'info' },
    ],
  },
  {
    id: 'agent-developer',
    name: 'Systems Architect',
    role: 'developer',
    purpose: 'Manages the technical layer. Audits code quality, flags vulnerabilities, monitors infrastructure, and proposes technical improvements.',
    status: 'idle',
    currentTask: null,
    model: 'claude-sonnet-4-6',
    capabilities: ['Code review', 'Security auditing', 'Infrastructure monitoring', 'Dependency management', 'Performance profiling'],
    lastActive: '2026-06-08T02:48:00Z',
    metrics: {
      tasksCompleted: 688,
      successRate: 89.4,
      avgResponseTime: 18.2,
      tokensUsed: 9800000,
      uptime: 94.1,
    },
    recentActivity: [
      { id: 'a21', timestamp: '2026-06-08T02:48:00Z', action: 'Dev ops audit — FAILED', result: 'GitHub API rate limit exceeded. Retry scheduled.', status: 'warn' },
      { id: 'a22', timestamp: '2026-06-07T02:01:00Z', action: 'Dependency vulnerability scan', result: '2 moderate CVEs found in lodash — ticket created', status: 'warn' },
      { id: 'a23', timestamp: '2026-06-06T02:02:00Z', action: 'Test coverage analysis', result: 'Coverage at 74.2% — below 80% threshold', status: 'info' },
      { id: 'a24', timestamp: '2026-06-05T02:01:00Z', action: 'Full codebase audit', result: 'No critical issues — 3 recommendations logged', status: 'success' },
    ],
  },
];

// ── TASKS ────────────────────────────────────────────────────────────────────

export const tasks: Task[] = [
  // BACKLOG
  { id: 't-001', title: 'Validate Series B fundraising deck narrative', description: 'Review and sharpen the narrative arc. Ensure data claims are defensible.', priority: 'high', agentId: 'agent-ceo', agentName: 'Strategic Command', dueDate: '2026-06-14', status: 'backlog', workflowId: null, tags: ['fundraising', 'strategy'], createdAt: '2026-06-07' },
  { id: 't-002', title: 'Map top 20 enterprise AI competitors', description: 'Full competitive landscape including pricing, ICP, GTM motion, and funding.', priority: 'high', agentId: 'agent-research', agentName: 'Intelligence Analyst', dueDate: '2026-06-13', status: 'backlog', workflowId: 'wf-001', tags: ['competitive', 'research'], createdAt: '2026-06-07' },
  { id: 't-003', title: 'Build outreach sequence for Operator tier', description: '5-step email sequence targeting founder-led SaaS companies with $1M+ ARR.', priority: 'medium', agentId: 'agent-sales', agentName: 'Revenue Intelligence', dueDate: '2026-06-16', status: 'backlog', workflowId: null, tags: ['sales', 'outreach'], createdAt: '2026-06-06' },
  { id: 't-004', title: 'Audit AWS infrastructure costs', description: 'Identify over-provisioned resources. Target 20% cost reduction.', priority: 'medium', agentId: 'agent-developer', agentName: 'Systems Architect', dueDate: '2026-06-20', status: 'backlog', workflowId: null, tags: ['infra', 'cost'], createdAt: '2026-06-05' },
  { id: 't-005', title: 'Draft partner integration proposal', description: 'Structure a business development proposal for data integration partners.', priority: 'low', agentId: 'agent-ceo', agentName: 'Strategic Command', dueDate: '2026-06-25', status: 'backlog', workflowId: null, tags: ['partnerships', 'bd'], createdAt: '2026-06-04' },

  // IN PROGRESS
  { id: 't-006', title: 'Q2 AI funding landscape analysis', description: 'Research and map all notable AI funding rounds in Q2 2026. Identify trends.', priority: 'high', agentId: 'agent-research', agentName: 'Intelligence Analyst', dueDate: '2026-06-09', status: 'in_progress', workflowId: null, tags: ['research', 'market'], createdAt: '2026-06-06' },
  { id: 't-007', title: 'Score 8 inbound waitlist leads', description: 'Evaluate each lead against founder ICP. Assign tier recommendation.', priority: 'critical', agentId: 'agent-sales', agentName: 'Revenue Intelligence', dueDate: '2026-06-08', status: 'in_progress', workflowId: 'wf-003', tags: ['leads', 'sales'], createdAt: '2026-06-08' },
  { id: 't-008', title: '"The Autonomous Operator" LinkedIn article', description: 'Long-form article on how AI changes operational leverage for founders.', priority: 'medium', agentId: 'agent-marketing', agentName: 'Growth Engine', dueDate: '2026-06-10', status: 'in_progress', workflowId: 'wf-005', tags: ['content', 'linkedin'], createdAt: '2026-06-07' },
  { id: 't-009', title: 'Fix GitHub API integration in dev audit', description: 'Rate limit error breaking the DevOps Audit workflow. Implement exponential backoff.', priority: 'critical', agentId: 'agent-developer', agentName: 'Systems Architect', dueDate: '2026-06-08', status: 'in_progress', workflowId: 'wf-008', tags: ['bug', 'engineering'], createdAt: '2026-06-08' },

  // REVIEW
  { id: 't-010', title: 'Board memo: Q2 competitive analysis', description: 'Strategic synthesis of competitive landscape for board consumption.', priority: 'critical', agentId: 'agent-ceo', agentName: 'Strategic Command', dueDate: '2026-06-09', status: 'review', workflowId: null, tags: ['board', 'strategy'], createdAt: '2026-06-05' },
  { id: 't-011', title: 'Anthropic pricing change impact analysis', description: 'Assess impact of new Anthropic pricing on NYX operating costs and margins.', priority: 'high', agentId: 'agent-finance', agentName: 'Financial Operator', dueDate: '2026-06-09', status: 'review', workflowId: null, tags: ['finance', 'pricing'], createdAt: '2026-06-07' },
  { id: 't-012', title: 'SEO content batch: June week 2', description: '3 articles targeting enterprise AI automation keywords.', priority: 'medium', agentId: 'agent-marketing', agentName: 'Growth Engine', dueDate: '2026-06-10', status: 'review', workflowId: 'wf-005', tags: ['content', 'seo'], createdAt: '2026-06-06' },

  // COMPLETED
  { id: 't-013', title: 'Executive briefing — June 8', description: 'Daily executive briefing covering priorities, signals, and recommendations.', priority: 'high', agentId: 'agent-ceo', agentName: 'Strategic Command', dueDate: '2026-06-08', status: 'completed', workflowId: 'wf-002', tags: ['briefing'], createdAt: '2026-06-08' },
  { id: 't-014', title: 'Competitor intelligence report — June 8', description: 'Daily competitive signals sweep across 22 tracked competitors.', priority: 'high', agentId: 'agent-research', agentName: 'Intelligence Analyst', dueDate: '2026-06-08', status: 'completed', workflowId: 'wf-001', tags: ['competitive'], createdAt: '2026-06-08' },
  { id: 't-015', title: 'Financial signal scan — 11:00 UTC', description: 'Hourly financial monitoring — macro signals, portfolio, FX.', priority: 'medium', agentId: 'agent-finance', agentName: 'Financial Operator', dueDate: '2026-06-08', status: 'completed', workflowId: 'wf-006', tags: ['finance', 'monitoring'], createdAt: '2026-06-08' },
  { id: 't-016', title: 'Lead: Priya Sharma / Helion Ventures', description: 'Research and qualify inbound lead from Helion Ventures founder.', priority: 'high', agentId: 'agent-sales', agentName: 'Revenue Intelligence', dueDate: '2026-06-08', status: 'completed', workflowId: 'wf-003', tags: ['lead', 'sales'], createdAt: '2026-06-07' },
];

// ── EXECUTIONS ───────────────────────────────────────────────────────────────

export const executions: Execution[] = [
  {
    id: 'exec-001',
    workflowId: 'wf-003',
    workflowName: 'Lead Qualification Engine',
    agentNames: ['Revenue Intelligence', 'Intelligence Analyst'],
    startTime: '2026-06-08T11:22:14Z',
    endTime: null,
    status: 'running',
    duration: null,
    result: null,
    triggeredBy: 'webhook',
    tokensUsed: 14200,
    outputSummary: null,
    logs: [
      { id: 'l1', timestamp: '2026-06-08T11:22:14Z', level: 'info', message: 'Execution started. Trigger: webhook. Payload: 8 leads received.', agentName: 'System' },
      { id: 'l2', timestamp: '2026-06-08T11:22:16Z', level: 'info', message: 'Enriching lead data from LinkedIn and Clearbit...', agentName: 'Intelligence Analyst' },
      { id: 'l3', timestamp: '2026-06-08T11:22:44Z', level: 'success', message: 'Lead enriched: Marcus Webb / Orbital Capital. ICP score: 88/100.', agentName: 'Intelligence Analyst' },
      { id: 'l4', timestamp: '2026-06-08T11:23:01Z', level: 'success', message: 'Lead enriched: Yuki Tanaka / Kaizen Systems. ICP score: 72/100.', agentName: 'Intelligence Analyst' },
      { id: 'l5', timestamp: '2026-06-08T11:23:18Z', level: 'success', message: 'Lead enriched: David Laurent / Nexus Partners. ICP score: 91/100.', agentName: 'Intelligence Analyst' },
      { id: 'l6', timestamp: '2026-06-08T11:23:35Z', level: 'info', message: 'Scoring remaining 5 leads against Operator tier ICP criteria...', agentName: 'Revenue Intelligence' },
    ],
  },
  {
    id: 'exec-002',
    workflowId: 'wf-001',
    workflowName: 'Competitor Intelligence',
    agentNames: ['Intelligence Analyst', 'Strategic Command'],
    startTime: '2026-06-08T06:00:00Z',
    endTime: '2026-06-08T06:04:44Z',
    status: 'success',
    duration: 284,
    result: 'Intelligence report generated. 847 signals processed. 12 flagged for executive attention. 3 critical developments identified.',
    triggeredBy: 'schedule',
    tokensUsed: 48200,
    outputSummary: 'Competitor intelligence report — June 8. Key findings: Notion AI launched agentic workflows (3 days ago). OpenAI announced custom GPT marketplace pricing change. Linear raised $35M Series C at $1.2B valuation.',
    logs: [
      { id: 'l10', timestamp: '2026-06-08T06:00:00Z', level: 'info', message: 'Scheduled execution started.', agentName: 'System' },
      { id: 'l11', timestamp: '2026-06-08T06:00:02Z', level: 'info', message: 'Scraping 22 competitor sites...', agentName: 'Intelligence Analyst' },
      { id: 'l12', timestamp: '2026-06-08T06:01:44Z', level: 'success', message: '22/22 sites scraped. 847 signals extracted.', agentName: 'Intelligence Analyst' },
      { id: 'l13', timestamp: '2026-06-08T06:01:45Z', level: 'info', message: 'Filtering and prioritizing signals...', agentName: 'Intelligence Analyst' },
      { id: 'l14', timestamp: '2026-06-08T06:02:30Z', level: 'warn', message: 'Critical signal: Notion AI agentic workflows — direct feature overlap detected.', agentName: 'Intelligence Analyst' },
      { id: 'l15', timestamp: '2026-06-08T06:03:10Z', level: 'info', message: 'Synthesizing executive summary...', agentName: 'Strategic Command' },
      { id: 'l16', timestamp: '2026-06-08T06:04:40Z', level: 'success', message: 'Report generated. Delivered to /briefings and Slack.', agentName: 'Strategic Command' },
      { id: 'l17', timestamp: '2026-06-08T06:04:44Z', level: 'success', message: 'Execution completed successfully. Duration: 4m 44s.', agentName: 'System' },
    ],
  },
  {
    id: 'exec-003',
    workflowId: 'wf-006',
    workflowName: 'Financial Signal Monitor',
    agentNames: ['Financial Operator'],
    startTime: '2026-06-08T11:00:00Z',
    endTime: '2026-06-08T11:00:22Z',
    status: 'success',
    duration: 22,
    result: 'No anomalies detected. All thresholds nominal.',
    triggeredBy: 'schedule',
    tokensUsed: 2100,
    outputSummary: 'Financial scan complete. MRR: $142,400. Burn rate: nominal. FX: nominal. Market signals: no critical alerts.',
    logs: [
      { id: 'l20', timestamp: '2026-06-08T11:00:00Z', level: 'info', message: 'Hourly financial signal scan initiated.', agentName: 'System' },
      { id: 'l21', timestamp: '2026-06-08T11:00:02Z', level: 'info', message: 'Fetching live FX rates, market indices, portfolio data...', agentName: 'Financial Operator' },
      { id: 'l22', timestamp: '2026-06-08T11:00:14Z', level: 'info', message: 'Running anomaly detection across 48 monitored metrics...', agentName: 'Financial Operator' },
      { id: 'l23', timestamp: '2026-06-08T11:00:22Z', level: 'success', message: 'Scan complete. 0 anomalies. 0 threshold breaches. Duration: 22s.', agentName: 'System' },
    ],
  },
  {
    id: 'exec-004',
    workflowId: 'wf-008',
    workflowName: 'Developer Ops Audit',
    agentNames: ['Systems Architect'],
    startTime: '2026-06-08T02:00:00Z',
    endTime: '2026-06-08T02:02:48Z',
    status: 'failed',
    duration: 168,
    result: 'Execution failed. GitHub API rate limit exceeded during repository scan.',
    triggeredBy: 'schedule',
    tokensUsed: 3800,
    outputSummary: null,
    logs: [
      { id: 'l30', timestamp: '2026-06-08T02:00:00Z', level: 'info', message: 'Developer ops audit started.', agentName: 'System' },
      { id: 'l31', timestamp: '2026-06-08T02:00:02Z', level: 'info', message: 'Initiating GitHub API authentication...', agentName: 'Systems Architect' },
      { id: 'l32', timestamp: '2026-06-08T02:00:04Z', level: 'info', message: 'Starting repository scan across 14 repositories...', agentName: 'Systems Architect' },
      { id: 'l33', timestamp: '2026-06-08T02:02:44Z', level: 'error', message: 'GitHub API error: 429 Too Many Requests. Rate limit: 5000/hr. Current: 5001.', agentName: 'Systems Architect' },
      { id: 'l34', timestamp: '2026-06-08T02:02:44Z', level: 'error', message: 'Retry attempt 1/3 failed. Exponential backoff not implemented.', agentName: 'Systems Architect' },
      { id: 'l35', timestamp: '2026-06-08T02:02:48Z', level: 'error', message: 'Execution failed. Ticket created: NYX-438 — Implement API rate limit handling.', agentName: 'System' },
    ],
  },
  {
    id: 'exec-005',
    workflowId: 'wf-002',
    workflowName: 'Weekly Executive Briefing',
    agentNames: ['Strategic Command', 'Intelligence Analyst', 'Financial Operator'],
    startTime: '2026-06-02T05:00:00Z',
    endTime: '2026-06-02T05:06:52Z',
    status: 'success',
    duration: 412,
    result: 'Weekly executive briefing generated and delivered. 3 priority items. 2 critical risks. 4 opportunities identified.',
    triggeredBy: 'schedule',
    tokensUsed: 82400,
    outputSummary: 'Week of June 2: Revenue on track ($142K MRR, +8.4% WoW). Product: 3 critical features shipped. Competitive: 2 new entrants in autonomous agents space. Recommendation: accelerate enterprise GTM.',
    logs: [
      { id: 'l40', timestamp: '2026-06-02T05:00:00Z', level: 'info', message: 'Weekly briefing workflow initiated.', agentName: 'System' },
      { id: 'l41', timestamp: '2026-06-02T05:00:04Z', level: 'info', message: 'Aggregating data from all agent outputs (7 days)...', agentName: 'Strategic Command' },
      { id: 'l42', timestamp: '2026-06-02T05:01:20Z', level: 'success', message: 'Financial data pulled. MRR: $142,400. Burn nominal.', agentName: 'Financial Operator' },
      { id: 'l43', timestamp: '2026-06-02T05:03:44Z', level: 'success', message: 'Intelligence synthesis complete. 12 competitive signals, 4 market signals.', agentName: 'Intelligence Analyst' },
      { id: 'l44', timestamp: '2026-06-02T05:05:10Z', level: 'info', message: 'Composing executive narrative...', agentName: 'Strategic Command' },
      { id: 'l45', timestamp: '2026-06-02T05:06:52Z', level: 'success', message: 'Briefing complete. Published to /briefings. Email delivered. Duration: 6m 52s.', agentName: 'System' },
    ],
  },
  {
    id: 'exec-006',
    workflowId: 'wf-004',
    workflowName: 'Startup Validation Framework',
    agentNames: ['Intelligence Analyst', 'Strategic Command'],
    startTime: '2026-06-07T14:30:00Z',
    endTime: '2026-06-07T14:42:00Z',
    status: 'success',
    duration: 720,
    result: 'Validation complete. "NexusAI" scored 74/100. Recommendation: Monitor, do not invest now.',
    triggeredBy: 'manual',
    tokensUsed: 61800,
    outputSummary: 'NexusAI validation: Strong team (ex-Palantir), limited market differentiation vs. existing players. Market timing early for SMB segment. Founder-market fit: 7/10. Recommend re-evaluate in 6 months.',
    logs: [
      { id: 'l50', timestamp: '2026-06-07T14:30:00Z', level: 'info', message: 'Manual validation triggered for "NexusAI".', agentName: 'System' },
      { id: 'l51', timestamp: '2026-06-07T14:30:02Z', level: 'info', message: 'Researching team backgrounds, funding history, product...', agentName: 'Intelligence Analyst' },
      { id: 'l52', timestamp: '2026-06-07T14:35:44Z', level: 'info', message: 'Mapping competitive landscape in NexusAI target segment...', agentName: 'Intelligence Analyst' },
      { id: 'l53', timestamp: '2026-06-07T14:40:10Z', level: 'info', message: 'Running scoring framework across 12 dimensions...', agentName: 'Strategic Command' },
      { id: 'l54', timestamp: '2026-06-07T14:42:00Z', level: 'success', message: 'Validation complete. Score: 74/100. Report delivered.', agentName: 'System' },
    ],
  },
];

// ── BRIEFING ─────────────────────────────────────────────────────────────────

export const briefing: Briefing = {
  date: '2026-06-08',
  classification: 'CONFIDENTIAL — OPERATOR LEVEL',
  generatedAt: '2026-06-08T06:01:22Z',
  generatedBy: 'Strategic Command (claude-opus-4-8)',
  systemScore: 91,
  executiveSummary: 'System operating at 91% efficiency. Revenue on track with $142,400 MRR (+8.4% WoW). Three competitive threats require attention: Notion AI agentic launch, OpenAI pricing adjustment, and Linear Series C signal. Lead pipeline strong with 8 high-ICP inbound contacts. Developer Ops Audit failure requires immediate resolution. Recommendation: prioritize enterprise GTM acceleration this week.',
  sections: [
    {
      id: 's-001',
      title: "Today's Priorities",
      type: 'priorities',
      summary: '4 items requiring action today. 1 critical, 2 high, 1 medium.',
      items: [
        { id: 'p1', content: 'Review and approve board memo on Q2 competitive landscape — draft in review queue', priority: 'critical', tags: ['board', 'strategy'] },
        { id: 'p2', content: 'Resolve GitHub API rate limit failure in DevOps Audit workflow (Ticket NYX-438)', priority: 'critical', tags: ['engineering', 'blocker'] },
        { id: 'p3', content: 'Review 8 inbound lead qualifications — Revenue agent completing scoring now', priority: 'high', tags: ['sales', 'pipeline'] },
        { id: 'p4', content: 'Approve outreach sequence for Operator tier before 18:00 UTC', priority: 'high', tags: ['sales', 'outreach'] },
      ],
    },
    {
      id: 's-002',
      title: 'Calendar Intelligence',
      type: 'calendar',
      summary: '3 events today. 1 requires preparation.',
      items: [
        { id: 'c1', content: 'Investor sync with Andreessen Horowitz — 14:00 UTC', time: '14:00 UTC', priority: 'high', tags: ['investors', 'fundraising'] },
        { id: 'c2', content: 'Weekly all-hands — 16:00 UTC. Agenda: Q2 roadmap, hiring plan', time: '16:00 UTC', priority: 'medium', tags: ['internal'] },
        { id: 'c3', content: 'Product review: autonomous workflow UI — 18:30 UTC', time: '18:30 UTC', priority: 'medium', tags: ['product'] },
        { id: 'c4', content: '[AI PREP] a16z sync: Prepare updated metrics deck. Highlight MRR growth trajectory and enterprise pipeline.', priority: 'critical', source: 'AI Recommendation', tags: ['preparation'] },
      ],
    },
    {
      id: 's-003',
      title: 'Signal Inbox',
      type: 'emails',
      summary: '6 emails flagged as requiring attention. 2 high-priority.',
      items: [
        { id: 'e1', content: 'David Laurent (Nexus Partners): "Interested in Operator tier — when can we connect?" — ICP score 91/100', source: 'david.laurent@nexuspartners.com', priority: 'high', tags: ['lead', 'hot'] },
        { id: 'e2', content: 'Stripe: Payment dispute filed for invoice #INV-0428 ($2,400) — requires response within 72h', source: 'disputes@stripe.com', priority: 'high', tags: ['billing', 'urgent'] },
        { id: 'e3', content: 'TechCrunch: Interview request on "AI operating systems" trend piece', source: 'press@techcrunch.com', priority: 'medium', tags: ['press', 'opportunity'] },
        { id: 'e4', content: 'Anthropic: API pricing change effective June 20 — review attached rate card', source: 'partnerships@anthropic.com', priority: 'medium', tags: ['vendor', 'cost'] },
        { id: 'e5', content: 'GitHub: Security advisory — 2 moderate CVEs in dependencies', source: 'noreply@github.com', priority: 'medium', tags: ['security'] },
        { id: 'e6', content: 'Priya Sharma (Helion Ventures): Following up on access request from last week', source: 'p.sharma@helion.vc', priority: 'low', tags: ['lead', 'follow-up'] },
      ],
    },
    {
      id: 's-004',
      title: 'Project Intelligence',
      type: 'projects',
      summary: '5 active projects. 1 at risk. 2 on track. 2 ahead of schedule.',
      items: [
        { id: 'pr1', content: 'NYX Dashboard (Phase 6): On track. Core features 80% complete. Launch target: June 20.', priority: 'high', tags: ['product', 'on-track'] },
        { id: 'pr2', content: 'Enterprise GTM: At risk. Sales pipeline $280K vs $400K target. 3 deals stalled.', priority: 'critical', tags: ['sales', 'at-risk'] },
        { id: 'pr3', content: 'Developer Infrastructure: 2 CVEs flagged, DevOps audit broken. Technical debt accumulating.', priority: 'high', tags: ['engineering', 'risk'] },
        { id: 'pr4', content: 'Content Engine: Ahead of schedule. 14 pieces published vs 10 target. 4,200 organic sessions projected.', priority: 'low', tags: ['marketing', 'ahead'] },
        { id: 'pr5', content: 'Series B Preparation: Board deck narrative in review. Data room 90% complete.', priority: 'high', tags: ['fundraising', 'in-progress'] },
      ],
    },
    {
      id: 's-005',
      title: 'Strategic Recommendations',
      type: 'recommendations',
      summary: '4 AI-generated recommendations based on current signals and data.',
      items: [
        { id: 'r1', content: 'Accelerate enterprise sales outreach. Pipeline gap of $120K vs target. 3 high-ICP leads waiting for contact.', priority: 'critical', source: 'Revenue Intelligence + Financial Operator', tags: ['sales', 'urgent'] },
        { id: 'r2', content: 'Respond to TechCrunch interview request. "AI operating systems" narrative gaining traction — 840 media mentions in last 30 days (+180%).', priority: 'high', source: 'Growth Engine', tags: ['pr', 'opportunity'] },
        { id: 'r3', content: 'Model Anthropic pricing impact before June 20. New rates may increase monthly API costs by 12–18%.', priority: 'high', source: 'Financial Operator', tags: ['cost', 'planning'] },
        { id: 'r4', content: 'Implement GitHub API rate limiting fix before tomorrow\'s audit window. Current failure streak: 1.', priority: 'high', source: 'Systems Architect', tags: ['engineering', 'blocker'] },
      ],
    },
    {
      id: 's-006',
      title: 'Risk Register',
      type: 'risks',
      summary: '3 active risks. 1 critical, 2 elevated.',
      items: [
        { id: 'rk1', content: 'Notion AI agentic workflow launch — direct feature overlap in core market. First-mover advantage window narrowing.', priority: 'critical', source: 'Intelligence Analyst', tags: ['competitive', 'product'] },
        { id: 'rk2', content: 'Enterprise sales pipeline below target by $120K. Q2 revenue miss possible if 3 stalled deals do not close.', priority: 'high', source: 'Revenue Intelligence', tags: ['revenue', 'sales'] },
        { id: 'rk3', content: 'Technical debt accumulation: 2 CVEs unpatched, test coverage below threshold, audit workflow broken.', priority: 'high', source: 'Systems Architect', tags: ['engineering', 'security'] },
      ],
    },
    {
      id: 's-007',
      title: 'Opportunity Matrix',
      type: 'opportunities',
      summary: '4 opportunities identified. 2 time-sensitive.',
      items: [
        { id: 'op1', content: 'TechCrunch interview: Category-defining PR moment. "AI operating systems" has no clear winner yet. NYX can own this narrative.', priority: 'high', source: 'Growth Engine', tags: ['pr', 'narrative'] },
        { id: 'op2', content: 'David Laurent (Nexus Partners, ICP 91/100) is actively evaluating Operator tier alternatives. Window: 48–72 hours.', priority: 'critical', source: 'Revenue Intelligence', tags: ['sales', 'time-sensitive'] },
        { id: 'op3', content: 'Linear Series C signal: Potential co-selling partnership opportunity. Integration would serve shared enterprise customer base.', priority: 'medium', source: 'Intelligence Analyst', tags: ['partnership', 'product'] },
        { id: 'op4', content: 'OpenAI GPT pricing increase creates switching opportunity for cost-sensitive customers. Draft comparison positioning.', priority: 'medium', source: 'Strategic Command', tags: ['competitive', 'marketing'] },
      ],
    },
  ],
};
